spring:
  application:
    name: bff-omdb
  profiles:
    active: local

omdb:
  api:
    url: https://www.omdbapi.com/
    key: ${OMDB_API_KEY:api-key}
    timeout: 30s

webclient:
  timeout:
    connection: 5s
    read: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    com.code.challenge.omdb.integration.bffomdb: INFO 